-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public."Books" DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public."Songs_Singers" DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public."Songs_Singers" DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public."Bios" DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public."Bios" DROP CONSTRAINT IF EXISTS None;



DROP TABLE IF EXISTS public."Authors";

CREATE TABLE IF NOT EXISTS public."Authors"
(
    id integer NOT NULL,
    name "char" NOT NULL,
    country "char",
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."Books";

CREATE TABLE IF NOT EXISTS public."Books"
(
    id integer NOT NULL,
    name "char" NOT NULL,
    "ISBN" "char",
    user_id integer NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."Singers";

CREATE TABLE IF NOT EXISTS public."Singers"
(
    id integer NOT NULL,
    name "char" NOT NULL,
    country "char",
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."Songs";

CREATE TABLE IF NOT EXISTS public."Songs"
(
    id integer NOT NULL,
    title "char" NOT NULL,
    album "char",
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."Songs_Singers";

CREATE TABLE IF NOT EXISTS public."Songs_Singers"
(
    "Songs_id" integer NOT NULL,
    "Singers_id" integer NOT NULL
);

DROP TABLE IF EXISTS public."Bios";

CREATE TABLE IF NOT EXISTS public."Bios"
(
    id integer NOT NULL,
    birthday date,
    death date,
    sumary text,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."Books"
    ADD FOREIGN KEY (user_id)
    REFERENCES public."Authors" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Songs_Singers"
    ADD FOREIGN KEY ("Songs_id")
    REFERENCES public."Songs" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Songs_Singers"
    ADD FOREIGN KEY ("Singers_id")
    REFERENCES public."Singers" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Bios"
    ADD FOREIGN KEY (id)
    REFERENCES public."Authors" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Bios"
    ADD FOREIGN KEY (id)
    REFERENCES public."Singers" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;